name: Test Self hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Print current directory
        run: pwd

      - name: List files
        run: ls -la
